// Curated content pool for the offline generator — HONEST edition (2026-07-16).
//
// The contract that makes the game defensible:
//   - Every `human` passage is real, attributed, public-domain human writing.
//     `source` names the author and work; "adapted" in a source means spelling
//     was modernized or the excerpt condensed, never that the substance changed.
//   - Every `ai` passage was genuinely produced by the model named in `model`.
//     Passages stamped "Claude Fable 5" were written by that model during the
//     2026-07-16 upgrade session; passages stamped "Claude (project-factory
//     build, 2026-07)" are from the factory's original build run — including
//     the ones deliberately styled to pass as human, which now (honestly)
//     serve as the hard tier.
//   - `tell` is the one-line lesson shown after a guess. `difficulty` is a
//     1 (easy) – 3 (hard) editorial rating.
//
// No fabricated attributions, ever: a model name a passage didn't come from is
// a bug, not flavor. Live generation against the current frontier model slots
// in via generate-bank.mjs --live (see docs/PIPELINE.md).

export const CONTENT_POOL = {
  human: [
    {
      id: "h-diary-scott-1",
      text: "Great God! this is an awful place and terrible enough for us to have laboured to it without the reward of priority.",
      style: "diary entry",
      source: "Capt. Robert Falcon Scott's diary at the South Pole, 17 January 1912",
      difficulty: 2,
    },
    {
      id: "h-diary-scott-2",
      text: "It seems a pity, but I do not think I can write more. For God's sake look after our people.",
      style: "diary entry",
      source: "Scott's final diary entry, Antarctica, March 1912",
      difficulty: 2,
    },
    {
      id: "h-diary-pepys-1",
      text: "We saw the fire grow in a most horrid malicious bloody flame, not like the fine flame of an ordinary fire. It made me weep to see it.",
      style: "diary entry",
      source: "Samuel Pepys on the Great Fire of London, 2 September 1666 (adapted)",
      difficulty: 3,
    },
    {
      id: "h-diary-darwin-1",
      text: "Delight itself, however, is a weak term to express the feelings of a naturalist who, for the first time, has wandered by himself in a Brazilian forest.",
      style: "diary entry",
      source: "Charles Darwin, Beagle diary, February 1832",
      difficulty: 2,
    },
    {
      id: "h-letter-keats-1",
      text: "I mean Negative Capability, that is, when a man is capable of being in uncertainties, mysteries, doubts, without any irritable reaching after fact and reason.",
      style: "letter",
      source: "John Keats to his brothers, 22 December 1817",
      difficulty: 2,
    },
    {
      id: "h-letter-adams-1",
      text: "I desire you would remember the ladies, and be more generous and favourable to them than your ancestors. Do not put such unlimited power into the hands of the husbands. Remember, all men would be tyrants if they could.",
      style: "letter",
      source: "Abigail Adams to John Adams, 31 March 1776",
      difficulty: 2,
    },
    {
      id: "h-letter-ballou-1",
      text: "If I do not return, my dear Sarah, never forget how much I love you, nor that, when my last breath escapes me on the battlefield, it will whisper your name.",
      style: "letter",
      source: "Maj. Sullivan Ballou to his wife, 14 July 1861 (adapted)",
      difficulty: 3,
    },
    {
      id: "h-travel-twain-1",
      text: "The gentle reader will never, never know what a consummate ass he can become until he goes abroad.",
      style: "travel note",
      source: "Mark Twain, The Innocents Abroad, 1869",
      difficulty: 2,
    },
    {
      id: "h-travel-bird-1",
      text: "Estes Park is mine. It is unsurveyed, no man's land, and mine by right of love, appropriation, and appreciation.",
      style: "travel note",
      source: "Isabella Bird, A Lady's Life in the Rocky Mountains, 1879 (adapted)",
      difficulty: 3,
    },
    {
      id: "h-news-london-1",
      text: "San Francisco is gone. Nothing remains of it but memories and a fringe of dwelling-houses on its outskirts.",
      style: "news lede",
      source: "Jack London reporting the 1906 earthquake for Collier's",
      difficulty: 2,
    },
    {
      id: "h-news-rice-1",
      text: "Outlined against a blue-gray October sky, the Four Horsemen rode again. In dramatic lore they are known as Famine, Pestilence, Destruction and Death. These are only aliases. Their real names are Stuhldreher, Miller, Crowley and Layden.",
      style: "news lede",
      source: "Grantland Rice's Notre Dame–Army lede, New York Herald Tribune, 1924",
      difficulty: 3,
    },
    {
      id: "h-recipe-beeton-1",
      text: "As with the commander of an army, or the leader of any enterprise, so is it with the mistress of a house.",
      style: "recipe intro",
      source: "Mrs Beeton's Book of Household Management, 1861 (adapted)",
      difficulty: 3,
    },
    {
      id: "h-recipe-farmer-1",
      text: "Progress in civilization has been accompanied by progress in cookery.",
      style: "recipe intro",
      source: "Fannie Farmer, Boston Cooking-School Cook Book, 1896 (adapted)",
      difficulty: 3,
    },
    {
      id: "h-telegram-benchley-1",
      text: "STREETS FULL OF WATER. PLEASE ADVISE.",
      style: "telegram",
      source: "Telegram attributed to Robert Benchley, on arriving in Venice",
      difficulty: 2,
    },
    {
      id: "h-nature-muir-1",
      text: "When we try to pick out anything by itself, we find it hitched to everything else in the Universe.",
      style: "nature note",
      source: "John Muir, My First Summer in the Sierra, 1911",
      difficulty: 2,
    },
    {
      id: "h-nature-thoreau-1",
      text: "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.",
      style: "nature note",
      source: "Henry David Thoreau, Walden, 1854",
      difficulty: 1,
    },
    {
      id: "h-review-twain-1",
      text: "I am trying to get the hang of this new fangled writing machine, but am not making a shining success of it.",
      style: "product review",
      source: "Mark Twain on his new typewriter, 1874 (adapted)",
      difficulty: 3,
    },
    // ——— Easy tier: humans with unmistakable voice — petty, specific, alive.
    // The warm-up contrast to the em-dash slop. ———
    {
      id: "h-letter-darwin-1",
      text: "But I am very poorly today and very stupid and hate everybody and everything.",
      style: "letter",
      source: "Charles Darwin to Charles Lyell, 1861",
      difficulty: 1,
    },
    {
      id: "h-overheard-johnson-1",
      text: "Depend upon it, sir, when a man knows he is to be hanged in a fortnight, it concentrates his mind wonderfully.",
      style: "overheard",
      source: "Samuel Johnson, quoted in Boswell's Life of Johnson, 1777",
      difficulty: 1,
    },
    {
      id: "h-letter-byron-1",
      text: "I have great hopes that we shall love each other all our lives as much as if we had never married at all.",
      style: "letter",
      source: "Lord Byron on his engagement, 1814 (adapted)",
      difficulty: 1,
    },
    {
      id: "h-diary-pepys-2",
      text: "This morning I put on my suit with great skirts, being resolved to appear handsome.",
      style: "diary entry",
      source: "Samuel Pepys's diary, 1660 (adapted)",
      difficulty: 1,
    },
    {
      id: "h-letter-pascal-1",
      text: "I have made this letter longer than usual, only because I have not had time to make it shorter.",
      style: "letter",
      source: "Blaise Pascal, Provincial Letters, 1657 (translated)",
      difficulty: 2,
    },
  ],
  ai: [
    // ——— Warm-up tier: written by Claude Fable 5 (2026-07-16), deliberately
    // saturated with the tells everyone memes about. The opening act — if you
    // know, you know, and you feel great about knowing. ———
    {
      id: "a-easy-email-1",
      text: "Hi team — just wanted to circle back on this. Let me know if you have questions, and don't hesitate to reach out!",
      style: "email",
      model: "Claude Fable 5",
      tell: "'Circle back' and 'don't hesitate to reach out' in the same three sentences — the corporate-email autopilot.",
      difficulty: 1,
    },
    {
      id: "a-easy-diary-1",
      text: "Today I delved into my morning routine — turns out a small change can shift your whole day.",
      style: "diary entry",
      model: "Claude Fable 5",
      tell: "Nobody 'delves into' a morning routine except a language model.",
      difficulty: 1,
    },
    {
      id: "a-easy-social-1",
      text: "Unpopular opinion: kindness is free — and it's contagious. Let that sink in.",
      style: "social post",
      model: "Claude Fable 5",
      tell: "An 'unpopular opinion' everyone already agrees with, plus the reflexive 'let that sink in.'",
      difficulty: 1,
    },
    {
      id: "a-easy-social-2",
      text: "Success isn't a destination — it's a journey. Read that again.",
      style: "social post",
      model: "Claude Fable 5",
      tell: "The 'it's not X, it's Y' cadence, capped with the 'read that again' sign-off.",
      difficulty: 1,
    },
    {
      id: "a-easy-review-1",
      text: "This isn't just a blender — it's an upgrade to your entire morning routine.",
      style: "product review",
      model: "Claude Fable 5",
      tell: "No blender has ever been described as an 'upgrade to your entire morning routine.'",
      difficulty: 1,
    },
    {
      id: "a-easy-news-1",
      text: "In a world where technology evolves at a breakneck pace, one local bakery is redefining what it means to rise. Their secret? A perfect blend of tradition and innovation.",
      style: "news lede",
      model: "Claude Fable 5",
      tell: "'In a world where…' — the movie-trailer opening no reporter has ever actually filed.",
      difficulty: 1,
    },
    {
      id: "a-easy-travel-1",
      text: "This hidden gem, tucked away in the old quarter, is an absolute must-visit — you won't be disappointed.",
      style: "travel note",
      model: "Claude Fable 5",
      tell: "'Hidden gem' and 'must-visit' in one sentence — the travel-cliché starter pack.",
      difficulty: 1,
    },
    {
      id: "a-easy-overheard-1",
      text: "Overheard at the gym: consistency isn't just a habit — it's a lifestyle.",
      style: "overheard",
      model: "Claude Fable 5",
      tell: "Nobody talks like a LinkedIn caption at the gym — but the em dash sure does.",
      difficulty: 1,
    },
    {
      id: "a-easy-chat-1",
      text: "You're absolutely right — I should have caught that. Let me fix it.",
      style: "chat log",
      model: "Claude Fable 5",
      tell: "The reflexive 'you're absolutely right' — the most-memed phrase in AI coding assistants.",
      difficulty: 1,
    },
    {
      id: "a-easy-recipe-2",
      text: "This soup comes together in twenty minutes — and it's even better the next day.",
      style: "recipe intro",
      model: "Claude Fable 5",
      tell: "No buzzwords at all — just a suspiciously tidy sentence and a suspiciously smooth dash.",
      difficulty: 1,
    },
    // ——— Mid tier additions (2026-07-16): plausible, quiet, slightly too tidy. ———
    {
      id: "a-recipe-weeknight-1",
      text: "Weeknight pasta for when the day won. Fifteen minutes, one pan, and the parmesan rind you forgot you saved doing most of the heavy lifting.",
      style: "recipe intro",
      model: "Claude Fable 5",
      tell: "Cozy and competent, but engineered — 'for when the day won' is a headline, not a memory.",
      difficulty: 2,
    },
    {
      id: "a-news-library-1",
      text: "The library's roof fund reached its goal Tuesday after an anonymous donor covered the final $4,200, ending a drive that began with a bake sale in March.",
      style: "news lede",
      model: "Claude Fable 5",
      tell: "Almost perfect wire copy — but every number resolves too neatly, like a story writing itself backward.",
      difficulty: 2,
    },
    {
      id: "a-letter-seeds-1",
      text: "Dear Sam — the seeds you sent came up in rows so straight I suspect them of ambition. Write when the harvest lets you.",
      style: "letter",
      model: "Claude Fable 5",
      tell: "Charming, but the wit is load-bearing — real farm letters spend more words on weather and debt.",
      difficulty: 2,
    },
    // ——— Period-voice hard tier: written by Claude Fable 5 (2026-07-16) to
    // pair against the real public-domain passages above. ———
    {
      id: "a-diary-polar-1",
      text: "Camped at last beneath the great ice barrier. The dogs are failing and the biscuit is short, yet I cannot bring myself to despair of the Pole. Tomorrow we shall know whether Providence intends us for glory or for graves.",
      style: "diary entry",
      model: "Claude Fable 5",
      tell: "Too rounded — real polar diaries log depots, mileage and frostbite, not matched pairs like “glory or graves.”",
      difficulty: 3,
    },
    {
      id: "a-diary-fire-1",
      text: "Up early, and to the river, where I did see the flames advancing most terribly upon the warehouses. Lord, what confusion of carts and crying children. And so home, much troubled in mind, and to bed.",
      style: "diary entry",
      model: "Claude Fable 5",
      tell: "A greatest-hits reel of Pepys signatures — “up early,” “Lord!,” “and so to bed” — all in four lines.",
      difficulty: 3,
    },
    {
      id: "a-travel-lady-1",
      text: "The pass was reported impassable, which I took, as usual, for an invitation. My pony disagreed at length and in Icelandic. We reached the hut long after dark, frozen quite through, and I have seldom been happier.",
      style: "travel note",
      model: "Claude Fable 5",
      tell: "Every sentence lands a punchline. Real Victorian travelers let some weather just be weather.",
      difficulty: 3,
    },
    {
      id: "a-letter-war-1",
      text: "My dearest, the army moves at dawn and I am told the work before us will be warm. Whatever befalls, know that my last thought marching shall be of you and of the little one I have not yet met.",
      style: "letter",
      model: "Claude Fable 5",
      tell: "A movie's idea of an 1861 letter — no regiment, no place, no mud. Only sentiment survived.",
      difficulty: 3,
    },
    {
      id: "a-news-period-1",
      text: "The city awoke to find the harbor empty, the fleet having slipped its moorings in the night. Officials profess no alarm, but the price of bread had doubled by noon, and the trains leaving town were full.",
      style: "news lede",
      model: "Claude Fable 5",
      tell: "Atmosphere over facts — a real wire lede names the city, the fleet, and the date in the first sentence.",
      difficulty: 3,
    },
    {
      id: "a-recipe-manual-1",
      text: "Let the young housekeeper remember that a dinner is judged not at the table but in the market. Buy honestly, waste nothing, and season with a light hand; guests forgive a plain dish sooner than a pretended one.",
      style: "recipe intro",
      model: "Claude Fable 5",
      tell: "Aphorisms stacked three deep. Period manuals mixed this register with brutally specific prices and weights.",
      difficulty: 3,
    },
    {
      id: "a-nature-pine-1",
      text: "In the pines I am never lonely, for every needle is a neighbor. The woods do not ask where I have been, and that is their whole hospitality.",
      style: "nature note",
      model: "Claude Fable 5",
      tell: "Aphorism-shaped nature. Muir counts species and miles; this counts metaphors.",
      difficulty: 3,
    },
    {
      id: "a-telegram-summit-1",
      text: "ARRIVED SUMMIT WEDNESDAY STOP OXYGEN LOW SPIRITS HIGH STOP WIRE MOTHER ALL WELL STOP SEND FUNDS AND MARMALADE.",
      style: "telegram",
      model: "Claude Fable 5",
      tell: "One joke too many — real telegrams economized on wit as strictly as on words.",
      difficulty: 3,
    },
    // ——— Modern-voice hard tier: the register people think AI can't do. ———
    {
      id: "a-diary-mri-1",
      text: "got the mri results and everything is fine which is great obviously but i'd already planned the whole speech for work about needing time off and now i just have a tuesday",
      style: "diary entry",
      model: "Claude Fable 5",
      tell: "Almost perfect — but the irony resolves too neatly, like the entry knew its own ending before it started.",
      difficulty: 3,
    },
    {
      id: "a-travel-dog-1",
      text: "The hostel guy drew the “real” route on my map in pencil and it added two hours and a dog that followed us the whole way. Would not trade the dog. Would maybe trade the hours.",
      style: "travel note",
      model: "Claude Fable 5",
      tell: "The callback structure — would not trade / would maybe trade — is a writer's move, rehearsed rather than remembered.",
      difficulty: 3,
    },
    {
      id: "a-recipe-cup-1",
      text: "My grandmother never measured anything and neither do I, except I absolutely do, secretly, with the same cracked cup she pretended not to use.",
      style: "recipe intro",
      model: "Claude Fable 5",
      tell: "One sentence doing three reversals. Real headnotes usually pick one memory and move on.",
      difficulty: 3,
    },
    {
      id: "a-news-council-1",
      text: "City council voted 6–1 Tuesday to extend the pilot program after residents packed the chamber for a third straight meeting, with the lone dissenter calling the data “thin as the parking it replaces.”",
      style: "news lede",
      model: "Claude Fable 5",
      tell: "The quote is too good. Beat reporters rarely get a dissenter this quotable, and never in the lede.",
      difficulty: 3,
    },
    {
      id: "a-review-rental-1",
      text: "Third one of these I've owned. Not because they break — I keep leaving them in rental cars. Buying in bulk now like some kind of forgetful king.",
      style: "product review",
      model: "Claude Fable 5",
      tell: "“Forgetful king” is the flourish of someone performing for upvotes — exactly the voice a model learns to imitate.",
      difficulty: 3,
    },
    // ——— Modern mid tier. ———
    {
      id: "a-diary-soup-1",
      text: "Rain all afternoon, so the errands lost by default. Made soup from whatever was left in the crisper and it was honestly better than the planned version. The cat supervised from the radiator.",
      style: "diary entry",
      model: "Claude Fable 5",
      tell: "Pleasant, specific-ish, and completely frictionless — nothing in it cost the writer anything.",
      difficulty: 2,
    },
    {
      id: "a-email-quote-1",
      text: "Just circling back on the quote from last week — totally understand if things slipped, the season's been chaos on our end too. If Thursday still works, we'll take it.",
      style: "email",
      model: "Claude Fable 5",
      tell: "Every clause pre-softens the next. Human follow-ups usually leave one edge unsanded.",
      difficulty: 2,
    },
    {
      id: "a-social-barista-1",
      text: "the barista spelled my name right today and honestly? that's the bar now. that's the whole bar.",
      style: "social post",
      model: "Claude Fable 5",
      tell: "Borrowed internet cadence — “honestly? that's the bar” — with no detail that pins it to an actual life.",
      difficulty: 2,
    },
    // ——— Factory build, styled-as-human: genuinely AI, deliberately messy.
    // Relabeled honestly (2026-07-16); they are the original hard tier. ———
    {
      id: "af-diary-umbrella-1",
      text: "Forgot my umbrella so I just accepted the rain. Walked home slow on purpose. There's a version of a bad day that's actually kind of nice if you stop fighting it.",
      style: "diary entry",
      model: "Claude (project-factory build, 2026-07)",
      tell: "The shrug is styled — “a version of a bad day” is an essayist's phrase wearing a diary's clothes.",
      difficulty: 3,
    },
    {
      id: "af-diary-treadmill-1",
      text: "The upstairs neighbor got a treadmill. I know this because it is 6am and I can hear the exact rhythm of a man giving up on jogging.",
      style: "diary entry",
      model: "Claude (project-factory build, 2026-07)",
      tell: "“The exact rhythm of a man giving up” is a punchline with a writers-room polish on it.",
      difficulty: 3,
    },
    {
      id: "af-review-zipper-1",
      text: "Zipper broke on day three. Emailed support, got a form reply, gave up. It's a fine bag if you never need the zipper, which, spoiler, is the entire point of a bag.",
      style: "product review",
      model: "Claude (project-factory build, 2026-07)",
      tell: "The “spoiler” aside and the neat rule-of-three arc are review-voice theater.",
      difficulty: 3,
    },
    {
      id: "af-review-catbox-1",
      text: "My cat likes the box it came in more than the actual scratching post. Five stars for the box. Two for the post. Averaging to what you see here.",
      style: "product review",
      model: "Claude (project-factory build, 2026-07)",
      tell: "The math bit lands too cleanly — a joke built backward from its own rating.",
      difficulty: 3,
    },
    {
      id: "af-news-ferry-1",
      text: "The ferry was cancelled for the third straight day, stranding a knot of commuters who traded weather rumors and cold coffee on the dock before giving up around nine.",
      style: "news lede",
      model: "Claude (project-factory build, 2026-07)",
      tell: "“A knot of commuters” is fine writing — but there's no ferry line, route, or official quoted anywhere.",
      difficulty: 3,
    },
    {
      id: "af-news-crosswalk-1",
      text: "Someone painted the crosswalk on Fifth over the weekend — not the city, someone. It's slightly crooked and everyone seems to like it more than the official ones.",
      style: "news lede",
      model: "Claude (project-factory build, 2026-07)",
      tell: "Charming, sourceless, and unfalsifiable — a vibe reported as an event.",
      difficulty: 3,
    },
    {
      id: "af-recipe-garlic-1",
      text: "You'll want more garlic than feels reasonable, then double it. My uncle taught me this and my uncle was wrong about most things but not this.",
      style: "recipe intro",
      model: "Claude (project-factory build, 2026-07)",
      tell: "The uncle exists only to deliver the reversal. Real headnote relatives come with one irrelevant detail.",
      difficulty: 3,
    },
    {
      id: "af-recipe-sauce-1",
      text: "This takes twenty minutes if you're honest and forty if you keep tasting the sauce, which you will, because the sauce is the whole reason you're here.",
      style: "recipe intro",
      model: "Claude (project-factory build, 2026-07)",
      tell: "Second-person mind-reading, twice, in one sentence — confidence no home cook writes with.",
      difficulty: 3,
    },
    {
      id: "af-social-gym-1",
      text: "saw a guy at the gym curling in the squat rack and honestly at this point i respect the commitment to being the villain of everyone's story",
      style: "social post",
      model: "Claude (project-factory build, 2026-07)",
      tell: "Assembled from two well-worn meme templates (squat-rack curls + “villain of everyone's story”).",
      difficulty: 3,
    },
    {
      id: "af-travel-temple-1",
      text: "The map said the temple was a ten minute walk. The map did not mention the ten minutes were vertical. Worth it, barely, mostly for the old woman selling oranges at the top.",
      style: "travel note",
      model: "Claude (project-factory build, 2026-07)",
      tell: "The orange seller is placed like a film's closing shot — one detail, perfectly weighted, suspiciously final.",
      difficulty: 3,
    },
    {
      id: "af-email-printer-1",
      text: "quick one — did we ever hear back from the printer about the poster sizes? no rush, just don't want to be the reason it's late again lol",
      style: "email",
      model: "Claude (project-factory build, 2026-07)",
      tell: "The “lol” is doing load-bearing casualness. The guilt is shaped exactly like a screenwriter's office worker.",
      difficulty: 3,
    },
    {
      id: "af-review-battery-1",
      text: "Bought it for the battery life everyone raves about. It's fine. It's a battery. It holds electricity and then it doesn't. I don't know what I expected to feel.",
      style: "product review",
      model: "Claude (project-factory build, 2026-07)",
      tell: "Ends on curated ennui — the existential beat is a bit, not a battery review.",
      difficulty: 3,
    },
    // ——— Factory build, classic register: the easy tier, kept honest. ———
    {
      id: "af-diary-gratitude-1",
      text: "Today reminded me how important it is to slow down and cherish the present moment. Life is full of small blessings, and taking time to notice them makes all the difference.",
      style: "diary entry",
      model: "Claude (project-factory build, 2026-07)",
      tell: "Even gratitude, zero specifics — the classic register. Nothing happened to anyone in particular.",
      difficulty: 1,
    },
    {
      id: "af-review-delivers-1",
      text: "This product truly delivers on its promises. The build quality is exceptional, the design is sleek and modern, and it has quickly become an essential part of my everyday life.",
      style: "product review",
      model: "Claude (project-factory build, 2026-07)",
      tell: "Three adjective pairs in a row and not one fact — no model number, no flaw, no life.",
      difficulty: 1,
    },
    {
      id: "af-news-community-1",
      text: "Community leaders came together this week to celebrate a new initiative designed to foster growth and collaboration. The event was met with enthusiasm from residents and officials alike.",
      style: "news lede",
      model: "Claude (project-factory build, 2026-07)",
      tell: "Who, where, what initiative? A lede with no nouns you could look up.",
      difficulty: 1,
    },
    {
      id: "af-recipe-wholesome-1",
      text: "This wholesome and satisfying dish is perfect for any occasion. Bursting with vibrant flavors and nutritious ingredients, it is sure to delight your family and impress your guests.",
      style: "recipe intro",
      model: "Claude (project-factory build, 2026-07)",
      tell: "“Perfect for any occasion” — brochure voice. No dish is named; none needs to be.",
      difficulty: 1,
    },
    {
      id: "af-travel-mustvisit-1",
      text: "This destination is an absolute must-visit for any traveler. From breathtaking landscapes to rich cultural experiences, every moment here offers something truly unforgettable and inspiring.",
      style: "travel note",
      model: "Claude (project-factory build, 2026-07)",
      tell: "A destination with no name, weather, or price — the postcard nobody sent.",
      difficulty: 1,
    },
  ],
};
